### PR TITLE
Makes viewer happy for now...

### PR DESCRIPTION
**Pull request by EnricoNirvana**

### CODE REVIEW

**Comment by greythane** [comment]
No problem with this but the in viewer location selection currently works in Singularity or viewers based on Singularity. 
Firestorm appears to ignore the location URI.
Angstrom was using it but with the 'hop' protocol.

Until the viewer developers can standardise on a format this will  be a 'work in progress'

**Comment by fly-man-** [comment]
I think the 'hop' protocol is loosely used in TPV viewers. If you teleport somewhere the response you see on your screen will show "You teleported from hop://server:port/regionname"

**Comment by emperorstarfinder** [comment]
The Hop protocol was the version of SLURL protocol used in Angstrom (possibly even Astra used it).  Most TPVs (Firestorm, Singularity, Kokua, Imprudence) use the SLURL but have some implementation of Hop due to Hypergrid.  LL did remove the URI from their viewer (but they also don't connect their viewer to Opensim based grids).  

In either event the only time the viewer looks for the welcomescreen is on the login page.  The rest of the time the only urls the viewer would look for is helper (for economy mostly) and support.  When logged in users usually have to use some form of a Hypergate to TP from one grid to another on the hypergrid (unless diva has done vast upgrades to this part).  When the viewer can't find the Welcomescreen it will usually return a 404 error on the login page. The note here to is the grid also has to have HG enabled in order for it to work.  Either way the viewers ignore what is sought to be fixed here as the viewer only looks for the welcome screen of the grid its attempting to log into on the login screen of the viewer.  Extensive viewer testing (I used Firestorm, Singularity, and will test this with Kokua as well) does not result in errors of the problem so would be interesting to know if an error was actually received or if this is more of a cleanup commit.

**Comment by EnricoNirvana** [comment]
100% agreed with EmperorStarFinder: the viewer looks for welcomescreen and the only purpose of SLURLs at login page is to land your avatar to the desired location. The commit was both: cleanup AND as a result of the error you would get: "your desired location was not available, you have been moved....blah blah" (obvious for a synthax like http://serverurl/region_name). But i'd agree with Grey too: let's call it a "work in progress". Actually the right synthax is: secondlife://region_name/X/Y/Z

**Comment by emperorstarfinder** [comment]
Ahhh the famous "your desired location was not available, you have been moved" message.  That has actually been fixed for quite some time in WhiteCore (i haven't seen it occur in over a year).  The reason you would get that actually has nothing to do with the welcome screen.  Usually you get it if a region location has changed, region is offline, etc.  Though you probably would still see that message in Opensim.

Viewers such as Singularity and Firestorm when you teleport now actually don't use secondlife://region_name/X/Y/Z now you will see http://example.com:8002/region_name/X/Y/Z for opensim (and whitecore based regions).  I would agree this does need some more standardization but it does seem to be slowly getting there with all the TPVs.  the secondlife://region_name/X/Y/Z was hardcoded in V1.23 and I think LL is still using it on their grid but you wouldn't want that in an opensim or whitecore based region as they aren't Secondlife.

**Comment by EnricoNirvana** [comment]
Then i will have a look at code since:
1.- Whitecore code before this commit at login page was secondlife://MainserverURL/region_name/x/y/z and it doesnt work right (gives you the "your location is actually unvailable..." message as it doesnt give you example.com:8002/region_name/x/y/z, but it gives you example.com/region_name/x/y/z)
2.- it should eventually be secondlife://MainserverURL:port/region_name/x/y/z
3.- if it did work for you, guys, before this commit, then you all prolly have the mainserver port @8002 and since i have it @80, i'd suspect it truncates the :80 with a slash "/" (like web browsers do) and makes it unhappy again....
Still "work in progress" and secondlife://region_name/x/y/z here...

**Comment by greythane** [comment]
Remember... this is an issue with the viewer coding, not WhiteCore.
During login, the viewer is the one requesting the location.

The version that Enrico fixed works for Singularity (based) viewers without problem. while Firestorm ignores the welcome screen links totally.  Angstrom is broken because it is looking for 'hop' protocols but is probably End of life unless someone has a desire to update it.

**Comment by emperorstarfinder** [comment]
Yes that would be correct.

If you have it set for example to http://example.com:80/ it is truncating very likely so that actually might give you headaches.  My comment was assuming you used port 8002/  

the SLURL issue that is more a viewer side issue as well.  However that being said I think if there is any uniformity being done there its probably coming from Firestorm as their developers appear to be on the other viewer development teams as well.  i.e. Cinder has contributed code to Firestorm, Singularity, Alchemy (and probably Kokua as well)

**Comment by nhede** [comment]
The hop protocol idea was copied from Kokua or Imprudence, and I made complete and working again and added some missing functionality. I think it was introduced by arminw but not 100% sure on that one. Back then the code looked like he tried to make hop:// the standard for opensim like grids. I used hop because it allows more functionality in the future and pointing to the proper grid and all. Sadly the leading viewers (singularity and firestorm) never picked up the more universal hop:// url thing.

A nice thing about the hop protocol, is that it allows for clicking the url in a normal browser, and from that it opens the viewer exe with the grid automatically added or selected. So new users don't have to do that "adding the grid" procedure.

Another thing that I had copied, is some preperations to allow alternative exe selection on a certain grid for voice communication.

**Comment by emperorstarfinder** [comment]
I think sadly the moral of this story will be, as long as viewers (i.e. Firestorm, Singularity, Kokua, etc.) cater to both the Secondlife and opensim based grids you won't really ever see any universal or uniform method of doing things especially with the Hop or SLURL.  The reason here partly is that by catering to Secondlife they are constrained somewhat by the Third Party Viewer policy adopted by the Labs (for better or worse take your pick) and its easier for them to just use the same boring SLURl protocol that way they don't have to take the hard time and do anything with it.

That said I do have to agree that Hop would be more of a complete standard to be using.

**Pull request merged**
